# Dataset Preparation 

In [5]:

import csv
import pandas as pd
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

#load data
AAPL_path = "./AAPL.csv"

df = pd.read_csv(AAPL_path)


print(AAPL_path)
print(df.head())




./AAPL.csv
         Date      Open      High       Low     Close  Adj Close       Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.023186  117258400.0
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.021977   43971200.0
2  1980-12-16  0.453125  0.453125  0.450893  0.450893   0.020364   26432000.0
3  1980-12-17  0.462054  0.464286  0.462054  0.462054   0.020868   21610400.0
4  1980-12-18  0.475446  0.477679  0.475446  0.475446   0.021473   18362400.0


In [6]:
# filter out dropping Date and Adj Close 

df_filtered = df.drop(columns=['Date', 'Adj Close'])
print("First 5 rows of the filtered data:")
print(df_filtered.head())

First 5 rows of the filtered data:
       Open      High       Low     Close       Volume
0  0.513393  0.515625  0.513393  0.513393  117258400.0
1  0.488839  0.488839  0.486607  0.486607   43971200.0
2  0.453125  0.453125  0.450893  0.450893   26432000.0
3  0.462054  0.464286  0.462054  0.462054   21610400.0
4  0.475446  0.477679  0.475446  0.475446   18362400.0


## Data Splitting and Preparation 70% Training data and 30 % test Date

In [7]:
from sklearn.model_selection import train_test_split

# Define input features and target variable
X_data = df_filtered[['Open', 'High', 'Low', 'Volume', 'Close']]  # Include 'Close' as an input feature
Y_data = df_filtered['Close']  # Target variable

# Split data into 70% training and 30% testing
X_data_train, X_data_test, Y_data_train, Y_data_test = train_test_split(
    X_data, Y_data, test_size=0.3, random_state=42
)

# Print shapes to confirm the split
print("X_data_train shape:", X_data_train.shape)
print("X_data_test shape:", X_data_test.shape)
print("Y_data_train shape:", Y_data_train.shape)
print("Y_data_test shape:", Y_data_test.shape)



X_data_train shape: (6689, 5)
X_data_test shape: (2867, 5)
Y_data_train shape: (6689,)
Y_data_test shape: (2867,)


## Normalizing the input features

In [8]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Fit the scaler on training data and transform both training and testing data
X_data_train_scaled = scaler.fit_transform(X_data_train)
X_data_test_scaled = scaler.transform(X_data_test)

# Confirm the normalization
print("Sample of scaled training data (first 5 rows):")
print(X_data_train_scaled[:5])


Sample of scaled training data (first 5 rows):
[[0.00110358 0.00120188 0.00110359 0.03047444 0.00116925]
 [0.006999   0.00695167 0.00689743 0.02363693 0.0068986 ]
 [0.00619067 0.00635554 0.00625695 0.01648095 0.0063627 ]
 [0.31317699 0.31596346 0.31704226 0.08142667 0.32020443]
 [0.47090254 0.47297309 0.47676629 0.01376061 0.479273  ]]


## Build the Fully-Connected Neural Network (FCNN)

In [16]:
# Define the FCNN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_data_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer with a single neuron for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mse'])




## Set Up Callbacks and Train the Model


In [19]:

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Set up callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_fcnn_model.keras', save_best_only=True, monitor='val_loss')

# Train the model
history = model.fit(
    X_data_train_scaled, Y_data_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping, model_checkpoint],
    verbose=1
)

# Print training completion
print("FCNN model training complete.")


Epoch 1/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 2/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 3/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 4/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 5/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 6/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 7/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 8/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 9/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 10/100
168/168 ━━━━━━━━━━━━━━━━

In [24]:
print("Number of NaNs in Y_data_test:", Y_data_test.isna().sum())


Number of NaNs in Y_data_test: 0


In [25]:
print("Number of NaNs in predictions:", np.isnan(predictions).sum())


Number of NaNs in predictions: 2867


In [26]:
print("Number of NaNs in X_data_train_scaled:", np.isnan(X_data_train_scaled).sum())
print("Number of NaNs in X_data_test_scaled:", np.isnan(X_data_test_scaled).sum())
print("Number of Infs in X_data_train_scaled:", np.isinf(X_data_train_scaled).sum())
print("Number of Infs in X_data_test_scaled:", np.isinf(X_data_test_scaled).sum())


Number of NaNs in X_data_train_scaled: 5
Number of NaNs in X_data_test_scaled: 0
Number of Infs in X_data_train_scaled: 0
Number of Infs in X_data_test_scaled: 0


In [27]:
nan_rows = X_data_train[X_data_train.isna().any(axis=1)]
print("Rows with NaN values in X_data_train:")
print(nan_rows)


Rows with NaN values in X_data_train:
     Open  High  Low  Volume  Close
165   NaN   NaN  NaN     NaN    NaN


In [35]:
# Get the index of rows with NaN values in X_data_train
nan_indices = X_data_train.index[X_data_train.isna().any(axis=1)]

# Drop the rows with NaN values from both X_data_train and Y_data_train
X_data_train = X_data_train.drop(index=nan_indices)
Y_data_train = Y_data_train.drop(index=nan_indices)

# Confirm the removal
print("Number of NaNs in X_data_train after removal:", X_data_train.isna().sum().sum())
print("Number of NaNs in Y_data_train after removal:", Y_data_train.isna().sum())



Number of NaNs in X_data_train after removal: 0
Number of NaNs in Y_data_train after removal: 0


## Re-normalize X_data_train

In [36]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Re-fit and transform the cleaned X_data_train
X_data_train_scaled = scaler.fit_transform(X_data_train)

# Transform X_data_test using the fitted scaler
X_data_test_scaled = scaler.transform(X_data_test)

# Confirm normalization
print("Sample of scaled training data (first 5 rows):")
print(X_data_train_scaled[:5])



Sample of scaled training data (first 5 rows):
[[0.00110358 0.00120188 0.00110359 0.03047444 0.00116925]
 [0.006999   0.00695167 0.00689743 0.02363693 0.0068986 ]
 [0.00619067 0.00635554 0.00625695 0.01648095 0.0063627 ]
 [0.31317699 0.31596346 0.31704226 0.08142667 0.32020443]
 [0.47090254 0.47297309 0.47676629 0.01376061 0.479273  ]]


## Re-training the Model:

In [37]:
# Re-train the model using the cleaned data
history = model.fit(
    X_data_train_scaled, Y_data_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping, model_checkpoint],
    verbose=1
)

# Generate predictions on the test set
predictions = model.predict(X_data_test_scaled)

# Check for NaNs in predictions
print("Number of NaNs in predictions after re-training:", np.isnan(predictions).sum())



Epoch 1/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 2/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 3/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 4/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 5/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 6/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 7/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 8/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 9/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 10/100
168/168 ━━━━━━━━━━━━━━━━

## Evaluate the Model and Plot the Regression Lift Chart

In [39]:
print("Number of NaNs in predictions:", np.isnan(predictions).sum())


Number of NaNs in predictions: 2867


In [41]:
from tensorflow.keras.optimizers import Adam

# Recompile the model with a lower learning rate
model.compile(optimizer=Adam(learning_rate=0.0001), loss='mean_squared_error', metrics=['mse'])


In [42]:
from tensorflow.keras.layers import Dropout

# Rebuild the model with dropout layers for regularization
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_data_train_scaled.shape[1],)),
    Dropout(0.3),  # Dropout to prevent overfitting
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(1)  # Output layer
])

# Recompile the model after adding dropout
model.compile(optimizer=Adam(learning_rate=0.0001), loss='mean_squared_error', metrics=['mse'])


C:\Users\Admin\anaconda3\envs\tf_env\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [43]:

print("Min and max of X_data_train_scaled:", X_data_train_scaled.min(), X_data_train_scaled.max())
print("Min and max of X_data_test_scaled:", X_data_test_scaled.min(), X_data_test_scaled.max())



Min and max of X_data_train_scaled: 0.0 1.0
Min and max of X_data_test_scaled: 3.845767079230136e-05 1.013463801591929


In [44]:
from tensorflow.keras.initializers import HeNormal

# Modify the model to include a different weight initializer
model = Sequential([
    Dense(64, activation='relu', kernel_initializer=HeNormal(), input_shape=(X_data_train_scaled.shape[1],)),
    Dropout(0.3),
    Dense(32, activation='relu', kernel_initializer=HeNormal()),
    Dropout(0.3),
    Dense(1)
])


In [45]:
from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt

# Calculate RMSE
rmse = np.sqrt(mean_squared_error(Y_data_test, predictions))
print("Test RMSE:", rmse)

# Plot the regression lift chart
plt.figure(figsize=(10, 6))
plt.scatter(Y_data_test, predictions, alpha=0.6)
plt.plot([min(Y_data_test), max(Y_data_test)], [min(Y_data_test), max(Y_data_test)], color='red')
plt.xlabel('Actual Close Prices')
plt.ylabel('Predicted Close Prices')
plt.title('Regression Lift Chart')
plt.show()


ValueError: Input contains NaN.